//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotiPetApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotiPetApp.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nosotros.
        /// </summary>
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información Adicional.
        /// </summary>
        internal static string Additiona_Information {
            get {
                return ResourceManager.GetString("Additiona Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar mascotas.
        /// </summary>
        internal static string AddPets {
            get {
                return ResourceManager.GetString("AddPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citas.
        /// </summary>
        internal static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que deseas cancelar el pedido?.
        /// </summary>
        internal static string Areyousurewanttocancelorder {
            get {
                return ResourceManager.GetString("Areyousurewanttocancelorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir ayuda.
        /// </summary>
        internal static string Askforhelp {
            get {
                return ResourceManager.GetString("Askforhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografía.
        /// </summary>
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinaria incorrecta.
        /// </summary>
        internal static string BusinessIdnotvalid {
            get {
                return ResourceManager.GetString("BusinessIdnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación .
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar cita.
        /// </summary>
        internal static string ConfirmAppointment {
            get {
                return ResourceManager.GetString("ConfirmAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear cita.
        /// </summary>
        internal static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de fecha.
        /// </summary>
        internal static string DateSelection {
            get {
                return ResourceManager.GetString("DateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe tu caso.
        /// </summary>
        internal static string Describeyourcase {
            get {
                return ResourceManager.GetString("Describeyourcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Todavía no tienes una cuenta en Notipet?.
        /// </summary>
        internal static string DonthaveaNotipetaccountyet {
            get {
                return ResourceManager.GetString("DonthaveaNotipetaccountyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergencia.
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte de tu información no es correcta, inténtalo de nuevo..
        /// </summary>
        internal static string ErrorLoginInformations {
            get {
                return ResourceManager.GetString("ErrorLoginInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenina.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Se te olvidó tu contraseña?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Como podemos ayudarte .
        /// </summary>
        internal static string Howcanwehelpyou {
            get {
                return ResourceManager.GetString("Howcanwehelpyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar .
        /// </summary>
        internal static string IAgreeToNotiPet {
            get {
                return ResourceManager.GetString("IAgreeToNotiPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizadas.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar un servicio.
        /// </summary>
        internal static string Mustselectaservice {
            get {
                return ResourceManager.GetString("Mustselectaservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis mascotas.
        /// </summary>
        internal static string MyPets {
            get {
                return ResourceManager.GetString("MyPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre incorrecto.
        /// </summary>
        internal static string Namenotvalid {
            get {
                return ResourceManager.GetString("Namenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donde tu mascota estará segura!!.
        /// </summary>
        internal static string OnBoarding1 {
            get {
                return ResourceManager.GetString("OnBoarding1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con seguimiento en tiempo real del estado de tus mascotas..
        /// </summary>
        internal static string OnBoarding2 {
            get {
                return ResourceManager.GetString("OnBoarding2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios de atención de urgencias para tus mascotas..
        /// </summary>
        internal static string OnBoarding3 {
            get {
                return ResourceManager.GetString("OnBoarding3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida.
        /// </summary>
        internal static string Passwordnotvalid {
            get {
                return ResourceManager.GetString("Passwordnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion personal.
        /// </summary>
        internal static string PersonalInformatión {
            get {
                return ResourceManager.GetString("PersonalInformatión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de mascota.
        /// </summary>
        internal static string Petsname {
            get {
                return ResourceManager.GetString("Petsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Mascota.
        /// </summary>
        internal static string PetType {
            get {
                return ResourceManager.GetString("PetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de mascota incorrecta.
        /// </summary>
        internal static string PetTypenotvalid {
            get {
                return ResourceManager.GetString("PetTypenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalue el servicio.
        /// </summary>
        internal static string Ratetheservice {
            get {
                return ResourceManager.GetString("Ratetheservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseñas.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento seleccionado:.
        /// </summary>
        internal static string Selecteddocumenttype {
            get {
                return ResourceManager.GetString("Selecteddocumenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección Mascotas.
        /// </summary>
        internal static string SelectionPets {
            get {
                return ResourceManager.GetString("SelectionPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debería estar entre {0} a {1}.
        /// </summary>
        internal static string Shouldbebetween {
            get {
                return ResourceManager.GetString("Shouldbebetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe elegir un tamaño.
        /// </summary>
        internal static string Sizenotvalid {
            get {
                return ResourceManager.GetString("Sizenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialistas.
        /// </summary>
        internal static string Specialists {
            get {
                return ResourceManager.GetString("Specialists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la especialidad:.
        /// </summary>
        internal static string SpecialityName {
            get {
                return ResourceManager.GetString("SpecialityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        internal static string TermsandConditions {
            get {
                return ResourceManager.GetString("TermsandConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximamente.
        /// </summary>
        internal static string UpComming {
            get {
                return ResourceManager.GetString("UpComming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario inválido.
        /// </summary>
        internal static string Usernamenotvalid {
            get {
                return ResourceManager.GetString("Usernamenotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacunas.
        /// </summary>
        internal static string Vaccines {
            get {
                return ResourceManager.GetString("Vaccines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinarios.
        /// </summary>
        internal static string Veterinaries {
            get {
                return ResourceManager.GetString("Veterinaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinaria.
        /// </summary>
        internal static string Veterinary {
            get {
                return ResourceManager.GetString("Veterinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar veterinaria.
        /// </summary>
        internal static string VeterinaryPicker {
            get {
                return ResourceManager.GetString("VeterinaryPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinaria Seleccionada:.
        /// </summary>
        internal static string VeterinarySelected {
            get {
                return ResourceManager.GetString("VeterinarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperándote a ti y a tu mascota.
        /// </summary>
        internal static string Waitingforyouandyoupet {
            get {
                return ResourceManager.GetString("Waitingforyouandyoupet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribir reseña.
        /// </summary>
        internal static string WriteReviews {
            get {
                return ResourceManager.GetString("WriteReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tu cita ha sido reservada!.
        /// </summary>
        internal static string Yourappointmenthasbooked {
            get {
                return ResourceManager.GetString("Yourappointmenthasbooked", resourceCulture);
            }
        }
    }
}
