//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotiPetApp.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NotiPetApp.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorLoginInformations {
            get {
                return ResourceManager.GetString("ErrorLoginInformations", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string DonthaveaNotipetaccountyet {
            get {
                return ResourceManager.GetString("DonthaveaNotipetaccountyet", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Selecteddocumenttype {
            get {
                return ResourceManager.GetString("Selecteddocumenttype", resourceCulture);
            }
        }
        
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string VeterinarySelected {
            get {
                return ResourceManager.GetString("VeterinarySelected", resourceCulture);
            }
        }
        
        internal static string IAgreeToNotiPet {
            get {
                return ResourceManager.GetString("IAgreeToNotiPet", resourceCulture);
            }
        }
        
        internal static string TermsandConditions {
            get {
                return ResourceManager.GetString("TermsandConditions", resourceCulture);
            }
        }
        
        internal static string Passwordnotvalid {
            get {
                return ResourceManager.GetString("Passwordnotvalid", resourceCulture);
            }
        }
        
        internal static string Usernamenotvalid {
            get {
                return ResourceManager.GetString("Usernamenotvalid", resourceCulture);
            }
        }
        
        internal static string BusinessIdnotvalid {
            get {
                return ResourceManager.GetString("BusinessIdnotvalid", resourceCulture);
            }
        }
        
        internal static string Shouldbebetween {
            get {
                return ResourceManager.GetString("Shouldbebetween", resourceCulture);
            }
        }
        
        internal static string Mustselectaservice {
            get {
                return ResourceManager.GetString("Mustselectaservice", resourceCulture);
            }
        }
        
        internal static string Namenotvalid {
            get {
                return ResourceManager.GetString("Namenotvalid", resourceCulture);
            }
        }
        
        internal static string PetTypenotvalid {
            get {
                return ResourceManager.GetString("PetTypenotvalid", resourceCulture);
            }
        }
        
        internal static string Sizenotvalid {
            get {
                return ResourceManager.GetString("Sizenotvalid", resourceCulture);
            }
        }
        
        internal static string OnBoarding1 {
            get {
                return ResourceManager.GetString("OnBoarding1", resourceCulture);
            }
        }
        
        internal static string OnBoarding2 {
            get {
                return ResourceManager.GetString("OnBoarding2", resourceCulture);
            }
        }
        
        internal static string OnBoarding3 {
            get {
                return ResourceManager.GetString("OnBoarding3", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string Veterinary {
            get {
                return ResourceManager.GetString("Veterinary", resourceCulture);
            }
        }
        
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        internal static string Howcanwehelpyou {
            get {
                return ResourceManager.GetString("Howcanwehelpyou", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        internal static string WriteReviews {
            get {
                return ResourceManager.GetString("WriteReviews", resourceCulture);
            }
        }
        
        internal static string SpecialityName {
            get {
                return ResourceManager.GetString("SpecialityName", resourceCulture);
            }
        }
        
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Askforhelp {
            get {
                return ResourceManager.GetString("Askforhelp", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Describeyourcase {
            get {
                return ResourceManager.GetString("Describeyourcase", resourceCulture);
            }
        }
        
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        internal static string Ratetheservice {
            get {
                return ResourceManager.GetString("Ratetheservice", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string AddPets {
            get {
                return ResourceManager.GetString("AddPets", resourceCulture);
            }
        }
        
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        internal static string Petsname {
            get {
                return ResourceManager.GetString("Petsname", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        internal static string PetType {
            get {
                return ResourceManager.GetString("PetType", resourceCulture);
            }
        }
        
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Vaccines {
            get {
                return ResourceManager.GetString("Vaccines", resourceCulture);
            }
        }
        
        internal static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string UpComming {
            get {
                return ResourceManager.GetString("UpComming", resourceCulture);
            }
        }
        
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        internal static string DateSelection {
            get {
                return ResourceManager.GetString("DateSelection", resourceCulture);
            }
        }
        
        internal static string SelectionPets {
            get {
                return ResourceManager.GetString("SelectionPets", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string ConfirmAppointment {
            get {
                return ResourceManager.GetString("ConfirmAppointment", resourceCulture);
            }
        }
        
        internal static string Yourappointmenthasbooked {
            get {
                return ResourceManager.GetString("Yourappointmenthasbooked", resourceCulture);
            }
        }
        
        internal static string Waitingforyouandyoupet {
            get {
                return ResourceManager.GetString("Waitingforyouandyoupet", resourceCulture);
            }
        }
        
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        internal static string Areyousurewanttocancelorder {
            get {
                return ResourceManager.GetString("Areyousurewanttocancelorder", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string MyPets {
            get {
                return ResourceManager.GetString("MyPets", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        internal static string VeterinaryPicker {
            get {
                return ResourceManager.GetString("VeterinaryPicker", resourceCulture);
            }
        }
        
        internal static string Specialists {
            get {
                return ResourceManager.GetString("Specialists", resourceCulture);
            }
        }
        
        internal static string Veterinaries {
            get {
                return ResourceManager.GetString("Veterinaries", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
    }
}
