name: Build, code quality, tests 

on:  
    push:
        branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build release 
      run: ./gradlew assembleRelease
    - name: App Center Distribute
      uses: devussy/AppCenter-Distribute-Github-Action@v1.0.5
      with:
        app: rafaelfDev/Dev Droid
        token: ${{43e70d2ba4280dc578baee3ca4259353d636aa4f}}
        group: Dev
        file: /Presentation/NotiPetApp/NotiPetApp.Droid/apk/
        silent: true
